stages:
  - build
  - test
  - review
  - stage
  - production

# branch build:
#   stage: build
#   # image: docker:19.03.12-dind
#   variables:
#     DOCKER_TLS_CERTDIR: ""
#   services:
#     - name: docker:dind
#       alias: docker
#   script:
#     - echo "Build to $CI_ENVIRONMENT_SLUG"
#     - docker info
#     - docker build -t reddit ./reddit
#   # environment:
#   #   name: branch/$CI_COMMIT_REF_NAME
#   #   url: http://$CI_ENVIRONMENT_SLUG.178.154.230.184.sslip.io
#   only:
#     - branches
#   except:
#     - master

branch_review:
  stage: review
  variables:
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:dind
      alias: docker
  before_script:
    # - apk update
    # - apk upgrade
    # - apk add --no-cache python python-dev py-pip build-base
    # - apk add --no-cache python-dev py-pip build-base libffi-dev openssl-dev
    # - apk add --no-cache curl jq python3 py3-pip gcc
    - apk add --update py3-pip
    - pip install --upgrade setuptools
    - pip install docker-compose
  script:
    - echo "Deploy to $CI_ENVIRONMENT_SLUG"
    - docker info
    # - docker build -t reddit ./reddit
    # - docker network create reddit
    # - docker run -d --network=reddit --network-alias=db mongo:latest
    # - docker run -d --network=reddit -p 9292:9292 reddit
    - docker-compose -f ./reddit/docker-compose.yml
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.178.154.230.184.sslip.io
  only:
    - branches
  except:
    - master

# staging:
#   stage: stage
#   when: manual
#   only:
#     - /^\d+\.\d+\.\d+/
#   script:
#     - echo 'Deploy'
#   environment:
#     name: beta
#     url: http://beta.178.154.230.184.sslip.io

# production:
#   stage: production
#   when: manual
#   script:
#     - echo 'Deploy'
#   environment:
#     name: production
#     url: http://178.154.230.184.sslip.io

# build_job:
#   stage: build
#   script:
#     - echo 'Building'

# test_unit_job:
#   stage: test
#   image: ruby:2.4.2
#   variables:
#     DATABASE_URL: 'mongodb://mongo/user_posts'
#   services:
#     - mongo:latest
#   before_script:
#     - cd reddit
#     - bundle install
#   script:
#     - ruby simpletest.rb

# test_integration_job:
#   stage: test
#   script:
#     - echo 'Testing 2'

# deploy_dev_job:
#   stage: review
#   script:
#     - echo 'Deploy'
#   environment:
#     name: dev
#     url: http://dev.178.154.230.184.sslip.io
