image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production

branch build:
  image: docker:19.03.8-dind
  services:
    - docker:19.03.12-dind
  stage: build
  script:
    - echo "Build to $CI_ENVIRONMENT_SLUG"
    - docker build -t reddit ./reddit
    - docker network create reddit
    - docker run -d --network=reddit --network-alias=db mongo:latest
    - docker run -d --network=reddit -p 9292:9292 reddit

  before_script:
    # - docker info
    # - cd reddit
    # - apt update
    # - apt install -y software-properties-common
    # - add-apt-repository ppa:deadsnakes/ppa
    # - apt update
    # - apt install -y python3.6-dev
    # - pip3 install --upgrade setuptools
    # - pip3 install docker-compose
    # - docker-compose up -d
  # command: puma
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: beta
    url: http://beta.example.com

production:
  stage: production
  when: manual
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  - cd reddit
  - bundle install

build_job:
  stage: build
  script:
    - echo 'Building'

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com
