version: '3.3'
services:
  mongo:
    image: mongo:${MONGO_TAG}
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - back_net

  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:9292
    networks:
      - front_net
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USERNAME}/post:${POST_VERSION}
    environment:
      - POST_DATABASE_HOST=mongo
      - POST_DATABASE=posts
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    depends_on:
      - mongo

  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    environment:
      - COMMENT_DATABASE_HOST=mongo
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net
    depends_on:
      - mongo

  # prometheus:
  #   image: ${USERNAME}/prometheus:${PROMETHEUS_VERSION}
  #   networks:
  #     - back_net
  #     - front_net
  #   ports:
  #   - '9090:9090'
  #   volumes:
  #   - prometheus_data:/prometheus
  #   command:
  #   - '--config.file=/etc/prometheus/prometheus.yml'
  #   - '--storage.tsdb.path=/prometheus'
  #   - '--storage.tsdb.retention=1d'

  # node-exporter:
  #   image: prom/node-exporter:v0.15.2
  #   networks:
  #     - back_net
  #   user: root
  #   volumes:
  #   - /proc:/host/proc:ro
  #   - /sys:/host/sys:ro
  #   - /:/rootfs:ro
  #   command:
  #   - '--path.procfs=/host/proc'
  #   - '--path.sysfs=/host/sys'
  #   - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  # mongo-exporter:
  #   image: ${USERNAME}/mongo-exporter:${MONGO_EXP_VERSION}
  #   environment:
  #     - MONGODB_URI=mongodb://mongo:27017
  #   networks:
  #     - back_net
  #   ports:
  #     - 9216:9216
  #   depends_on:
  #     - mongo

  # blackbox-exporter:
  #   image: ${USERNAME}/blackbox:${BLACKBOX_VERSION}
  #   networks:
  #     - front_net
  #   user: root
  #   ports:
  #     - 9115:9115

volumes:
  mongo:
  prometheus_data:

networks:
  front_net:
  back_net:
