---
- name: Cleaning Up
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Cleaning Up
    shell:
      cmd: |
        yc compute instance delete controller-0 controller-1 controller-2 worker-0 worker-1 worker-2

        yc load-balancer network-load-balancer delete kubernetes-forwarding-rule
        yc load-balancer target-group delete kubernetes-target-pool
        yc vpc address delete kubernetes-the-hard-way

        for i in 0 1 2; do
          yc vpc route-table delete kubernetes-route-10-200-${i}-0-24
        done

        yc vpc subnet delete kubernetes

        yc vpc networks delete kubernetes-the-hard-way

        rm ../inventory.ini
