---
- name: Install soft
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: Create the etcd.service systemd unit file
      shell:
        cmd: |
          wget -q --show-progress --https-only --timestamping https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/1.4.1/linux/cfssl https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/1.4.1/linux/cfssljson
          chmod +x cfssl cfssljson
          sudo mv cfssl cfssljson /usr/local/bin/
          sudo apt-get install -y jq
          wget https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

  # - name: Download cfssl
  #   get_url:
  #     url: https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/1.4.1/linux/cfssl
  #     dest: /usr/local/bin/
  #     mode: +x

  # - name: Download cfssljson
  #   get_url:
  #     url: https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/1.4.1/linux/cfssljson
  #     dest: /usr/local/bin/
  #     mode: +x

  # - name: Install required system packages
  #   apt: name=jq state=latest update_cache=yes

  # - name: Download kubectl
  #   get_url:
  #     url: https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/kubectl
  #     dest: /usr/local/bin/
  #     mode: +x
